gesLoc = {
  "ABJCAYA": "Abidjan (Ivory Coast)",
  "ACCFAYA": "Accra (Ghana)",
  "AKLCDYA": "Auckland Oceanic (NZ)",
  "ALGCAYA": "Alger (Algeria)",
  "ANCATYA": "Anchorage Oceanic (USA)",
  "ANCXFXA": "Anchorage Domestic (USA)",
  "AUHABYA": "",
  "AUHCAYA": "",
  "BAHCEYA": "",
  "BDOCAYA": "Bodo Oceanic (Norway)",
  "BJSATYA": "",
  "BJSGWYA": "Beijing (China)",
  "BKKCAYA": "Thailand",
  "BKKGWXA": "Bangkok (Thailand)",
  "BNECAYA": "Brisbane (AUS)",
  "BOMCAYA": "Mumbai (India)",
  "BOMCDYA": "",
  "BZVCAYA": "Brazzaville (Congo)",
  "CAICAYA": "Egypt",
  "CAICDYA": "Cairo (Egypt)",
  "CANGWYA": "Guangzhou (China)",
  "CAYCAYA": "Cayenne (French Guiana)",
  "CCUCAYA": "Kolkata (India)",
  "CCUCBYA": "Kolkata (India)",
  "CDGATYA": "Paris (France)",
  "CMBCAYA": "Colombo (Sri Lanka)",
  "CMBCBYA": "Colombo (Sri Lanka)",
  "CTUGWYA": "Chengdu (China)",
  "DATSAXS": "",
  "DDLCVXA": "Bodo (Norway)",
  "DELCAYA": "Delhi (India)",
  "DKRCAYA": "Dakar Oceanic (Senegal)",
  "DOHATYA": "Doha (Qatar)",
  "DXBEGEK": "",
  "FIHCAYA": "Congo",
  "FUKJJYA": "Fukuoka (Japan)",
  "GDXE1XA": "Magadan (Russia)",
  "GDXGWXA": "Magadan (Russia)",
  "GVACBYA": "",
  "GVSCAYA": "Sal Oceanic (Cape Verde)",
  "GYDCDYA": "",
  "HDQOILX": "",
  "HKGCCYA": "Hong Kong",
  "HRBGWYA": "Harbin (China)",
  "JAKGWXA": "Jakarta (Indonesia)",
  "JEDAAYA": "",
  "JEDATYA": "",
  "JNBCAYA": "Johannesburg Oceanic (SA)",
  "KANCAYA": "Kano (Nigeria)",
  "KMGGWYA": "Kunming (China)",
  "KRTCAYA": "Khartoum (Sudan)",
  "KRTCDYA": "Sudan",
  "KULCAYA": "Kuala Lumpur (Malaysia)",
  "LADCAYA": "Angola (Luanda)",
  "LHWGWYA": "Lanzhou (China)",
  "LISACYA": "Lisboa (Portugal)",
  "LPAFAYA": "Canarias (Spain)",
  "LXAGWYA": "Lhasa (China)",
  "MAACAYA": "Chennai (India)",
  "MADAAYA": "",
  "MADCDYA": "",
  "MCTASWY": "Muscat (Oman)",
  "MELCAYA": "Melbourne (AUS)",
  "MEXCAYA": "Mexico",
  "MGQCAYA": "Ethiopia",
  "MLECAYA": "Male (Maldives)",
  "MNLCBYA": "Manila (Philippines)",
  "MRUCAYA": "Mauritius (Mauritius)",
  "MSTEC7X": "Maastricht (NL)",
  "NANCDYA": "Nadi (Fiji)",
  "NBOCAYA": "Kenya (Niarobi)",
  "NDJCAYA": "N'Djamena (Chad)",
  "NIMCAYA": "Niamey (Niger)",
  "NKCCAYA": "Dakar Domestic (Senegal)",
  "NYCODYA": "New York Oceanic (USA)",
  "OAKODYA": "Oakland Oceanic (USA)",
  "PAREUYA": "France",
  "PIKCAYA": "Scottish (UK)",
  "PIKCLXS": "Prestwick Domestic (UK)",
  "PIKCLYA": "Prestwick Oceanic (UK)",
  "PIKCPYA": "Shanwick (UK)",
  "POMCAYA": "Port Moresby (PG)",
  "POSCLYA": "Piarco (Trinidad)",
  "PPTCDYA": "Tahiti (French Polynesia)",
  "RECOEYA": "Atlantico (Brazil)",
  "REKCAYA": "Reykjavik (Iceland)",
  "RGNCAYA": "Yangon (Myanmar)",
  "RIOCDYA": "",
  "RPHIAYA": "Manila (Philippines)",
  "RUHAAYA": "",
  "SCLCAYA": "Antofagasta (Chile)",
  "SELCAXH": "Seoul (Korea)",
  "SEZCAYA": "Seychelles",
  "SGNGWXA": "Ho Chi Minh (Vietnam)",
  "SHAGWYA": "Shanghai (China)",
  "SINCDYA": "Singapore",
  "SINCXYA": "Singapore",
  "SMACAYA": "Santa Maria (Portugal)",
  "SNNCPXA": "Shannon (Ireland)",
  "SOUCAYA": "London (UK)",
  "SPLATYA": "Amsterdam Schipol (NL)",
  "TASCAXH": "Tashkent (Uzbekistan)",
  "TGUACAY": "Honduras (Cenamer)",
  "TGUACYA": "Cenamar (Honduras)",
  "TNRCAYA": "Antananarivo (Madagascar)",
  "ULNGWXA": "Ulan Bataar (Mongolia)",
  "UPGCAYA": "Makassar (Indonesia)",
  "URCE1YA": "Urumqi (China)",
  "URCGWYA": "Urum-Qi (China)",
  "USADCXA": "USA Domestic (USA)",
  "YEGCDYA": "Edmonton (Canada)",
  "YEGE2YA": "Edmonton (Canada)",
  "YQME2YA": "Moncton (Canada)",
  "YQXD2YA": "Gander Domestic (Canada)",
  "YQXE2YA": "Gander Oceanic (Canada)",
  "YULE2YA": "Montreal (Canada)",
  "YVRE2YA": "Vancouver (Canada)",
  "YWGE2YA": "Winnipeg (Canada)",
  "YYZE2YA": "Toronto (Canada)"
}

def geslookup(gsa):
  txt = gesLoc.get(gsa)
  if not txt:
    pass
  return txt
