name: Build and deploy to ghcr.io

on:
  workflow_dispatch:
    inputs:
      reason:
        required: true
        description: 'Reason for running this workflow'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
    - name: "Build:checkout"
      uses: actions/checkout@v4

    - name: "Build:buildx"
      uses: docker/setup-buildx-action@v3

    - name: "Build:login"
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Build:buildandpush'
      uses: docker/build-push-action@v6
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${{ github.run_number }}-${{ github.sha }}
